# Generated by Django 6.0.3 on 2026-03-28 11:51

import django.contrib.postgres.indexes
import django.db.models.deletion
import property.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0001_enable_pg_trgm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('license_number', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=property.models.get_file_path)),
                ('suburb', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('property_type', models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('townhouse', 'Townhouse'), ('land', 'Land')], default='house', max_length=20)),
                ('internal_notes', models.TextField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='property.agent')),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'indexes': [models.Index(fields=['price'], name='property_pr_price_b1d594_idx'), models.Index(fields=['suburb'], name='property_pr_suburb_b7f0cf_idx'), models.Index(fields=['property_type'], name='property_pr_propert_01098c_idx'), models.Index(fields=['bedrooms'], name='property_pr_bedroom_6d8f3c_idx'), django.contrib.postgres.indexes.GinIndex(fields=['title', 'description'], name='property_search_gin', opclasses=['gin_trgm_ops', 'gin_trgm_ops'])],
            },
        ),
    ]
